export AWS_DEFAULT_REGION="CHANGE_ME"
export AWS_ACCESS_KEY_ID="CHANGE_ME"
export AWS_SECRET_ACCESS_KEY="CHANGE_ME"
export AWS_SESSION_TOKEN="CHANGE_ME"

export OPENAI_API_KEY="CHANGE_ME"

export FLASK_DB_HOST="CHANGE_ME"
export FLASK_DB_USER="CHANGE_ME"
export FLASK_DB_PASS="CHANGE_ME"

export FLASK_JWT_SECRET_KEY="CHANGE_ME"

export FLASK_DYNAMODB_USERS_TABLE="CHANGE_ME"
export FLASK_S3_IMAGES_BUCKET="CHANGE_ME"
